#!/bin/bash
#===================================================================================
# FILE: welcome
# DESCRIPTION: show yad dialog with Openbox welcome text
# AUTHOR: Adam Singer 
# VERSION: 1.0
# CREATED: 2010.08.12
# LICENSE: GNU General Public License v3.0
#===================================================================================

welcome_link=~/.config/openbox/welcome

# English welcome text
text_en='<big><b>WELCOME TO LUKEOS SCRIPT!</b></big>
 A lightweight and minimal desktop on Debian!. There are some <b>tips</b>:

 <b> How to open main menu?</b>
   • Right click on desktop and taskbar
   • Right click on left screen border (even if there are maximized windows)
<b> How to exit/power off?</b>
   • <tt>Main menu > Exit</tt>
   • <tt>WIN+x</tt>
<b> How to snap Windows?</b>
   • Middle clic on title bar
   • <tt>WIN+arrows</tt>
   • <tt>WIN+[0-9]</tt>
   
<b> Search commands</b>		<tt>WIN</tt>
<b> Move windows</b>			<tt>ALT+left click</tt> (and drag)
<b> Resize windows</b>			<tt>ALT+right click</tt> (and drag)
<b> Window always on top</b>		<tt>WIN+0</tt>
<b> Kill X server</b>				<tt>CTRL+ALT+BACKSPACE</tt>

<b> Open terminal</b>			<tt>WIN+t</tt>
<b> Open file manager</b>		<tt>WIN+f</tt>
<b> Open web browser</b>		<tt>WIN+w</tt>
<b> Open editor</b>				<tt>WIN+e</tt>
'
field_en="Show this message on startup"

# Get current language
lang="en"
[ "$(echo $LANG | cut -f1 -d_)" = "es" ] && lang="es"
eval text="\$text_$lang"
eval field="\$field_$lang"

# Show yad dialog
output=$(yad --form --button=gtk-ok --center --undecorated --fixed --borders=30 --window-icon=nautilus --text="$text" --field="$field:CHK" $([ -s "$welcome_link" ] && echo true || echo false) --separator=""  --image=debian-logo)

# Delete simbolic link if not show next time is checked
if [ "$output" = "FALSE" ]; then
	rm ~/.config/openbox/welcome &>/dev/null
else
	ln -s /usr/bin/welcome "$welcome_link" &>/dev/null
fi


